sensio_framework_extra:
  router:
    annotations: false

  request:
    converters: true # note for custom resolver - PostFilterRequest
    auto_convert: false # note for custom resolver - PostFilterRequest